const companies = [
  {
    id: 1,
    name: "Thousand Hills Accounting Ldt",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Finance, Account, etc..",
    status: true,
  },
  {
    id: 2,
    name: "Tiger Chat",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Finance, Account, Project Management",
    status: false,
  },
  {
    id: 3,
    name: "Buffalo Trading",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Marketing, Account",
    status: true,
  },
  {
    id: 4,
    name: "Giraffe Company",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "E-commerce",
    status: false,
  },
  {
    id: 5,
    name: "Cow Farming",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Finance, Account, etc..",
    status: false,
  },
  {
    id: 6,
    name: "Deer Cosmetics",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Finance, Account, etc..",
    status: true,
  },
  {
    id: 7,
    name: "Bear Power - Energy drinks",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Finance, Account, etc..",
    status: false,
  },
  {
    id: 8,
    name: "Fox Delivery company",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Finance, Account, etc..",
    status: false,
  },
  {
    id: 9,
    name: "Wolf Events Organizers",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Finance, Account, etc..",
    status: false,
  },
  {
    id: 10,
    name: "Gorilla Tourism Company",
    createdAt: "12/12/2020",
    type: "Enabler",
    areaOfInterest: "Finance, Account, etc..",
    status: false,
  },
];

export default companies;
