const content = [
  {
    title: 1,
    author: "Kareem Scrannage",
    category: "AI",
    tag: "Health Tech",
    date: "4/5/2020",
    status: false,
  },
  {
    title: 2,
    author: "Riane Pratty",
    category: "AI",
    tag: "Mobility",
    date: "10/13/2020",
    status: false,
  },
  {
    title: 3,
    author: "Tabor Southerill",
    category: "AI",
    tag: "Health Tech",
    date: "12/24/2019",
    status: false,
  },
  {
    title: 4,
    author: "Winny Burgh",
    category: "Cyber security",
    tag: "Mobility",
    date: "5/2/2020",
    status: false,
  },
  {
    title: 5,
    author: "Wendy Twiname",
    category: "AI",
    tag: "Security",
    date: "10/25/2020",
    status: false,
  },
  {
    title: 6,
    author: "Camella Rehn",
    category: "Cyber security",
    tag: "Security",
    date: "1/19/2020",
    status: false,
  },
  {
    title: 7,
    author: "Juline Josskowitz",
    category: "Cyber security",
    tag: "Health Tech",
    date: "9/3/2020",
    status: true,
  },
  {
    title: 8,
    author: "Jacklyn Cheshire",
    category: "Cyber security",
    tag: "Health Tech",
    date: "9/24/2020",
    status: false,
  },
  {
    title: 9,
    author: "Amy McFayden",
    category: "Cyber security",
    tag: "Mobility",
    date: "10/11/2020",
    status: true,
  },
  {
    title: 10,
    author: "Alan Trevains",
    category: "Cyber security",
    tag: "Mobility",
    date: "8/25/2020",
    status: false,
  },
  {
    title: 11,
    author: "Markus Showler",
    category: "AI",
    tag: "Health Tech",
    date: "1/18/2020",
    status: true,
  },
  {
    title: 12,
    author: "Elisabeth Ebanks",
    category: "Cyber security",
    tag: "Health Tech",
    date: "5/23/2020",
    status: true,
  },
  {
    title: 13,
    author: "Brena Romagosa",
    category: "AI",
    tag: "Health Tech",
    date: "10/18/2020",
    status: false,
  },
  {
    title: 14,
    author: "Melany Wanka",
    category: "AI",
    tag: "Security",
    date: "2/3/2020",
    status: false,
  },
  {
    title: 15,
    author: "Fax Midner",
    category: "AI",
    tag: "Mobility",
    date: "3/22/2020",
    status: true,
  },
  {
    title: 16,
    author: "Doug Wittey",
    category: "AI",
    tag: "Security",
    date: "7/13/2020",
    status: true,
  },
  {
    title: 17,
    author: "Christel Knapman",
    category: "Cyber security",
    tag: "Security",
    date: "9/5/2020",
    status: true,
  },
  {
    title: 18,
    author: "Wilden Ginnaly",
    category: "AI",
    tag: "Health Tech",
    date: "12/23/2019",
    status: false,
  },
  {
    title: 19,
    author: "Barbey Bergstrand",
    category: "Cyber security",
    tag: "Mobility",
    date: "5/9/2020",
    status: true,
  },
  {
    title: 20,
    author: "Marcie Wanstall",
    category: "AI",
    tag: "Mobility",
    date: "2/2/2020",
    status: false,
  },
  {
    title: 21,
    author: "Shelby Pirie",
    category: "AI",
    tag: "Mobility",
    date: "7/20/2020",
    status: true,
  },
  {
    title: 22,
    author: "Lanna Flitcroft",
    category: "AI",
    tag: "Mobility",
    date: "11/7/2020",
    status: false,
  },
  {
    title: 23,
    author: "Reinwald Binner",
    category: "Cyber security",
    tag: "Health Tech",
    date: "10/18/2020",
    status: false,
  },
  {
    title: 24,
    author: "Osmond Gittis",
    category: "AI",
    tag: "Security",
    date: "1/14/2020",
    status: false,
  },
  {
    title: 25,
    author: "Kerstin Dodsworth",
    category: "AI",
    tag: "Health Tech",
    date: "11/30/2019",
    status: false,
  },
  {
    title: 26,
    author: "Fan Rate",
    category: "AI",
    tag: "Mobility",
    date: "8/2/2020",
    status: false,
  },
  {
    title: 27,
    author: "Dacey McWhinnie",
    category: "AI",
    tag: "Mobility",
    date: "12/2/2019",
    status: true,
  },
  {
    title: 28,
    author: "Tricia Palek",
    category: "AI",
    tag: "Health Tech",
    date: "12/2/2019",
    status: false,
  },
  {
    title: 29,
    author: "Giuseppe Back",
    category: "AI",
    tag: "Security",
    date: "12/23/2019",
    status: false,
  },
  {
    title: 30,
    author: "Talyah Luttgert",
    category: "Cyber security",
    tag: "Security",
    date: "10/6/2020",
    status: true,
  },
  {
    title: 31,
    author: "Anthony Bullar",
    category: "AI",
    tag: "Security",
    date: "4/3/2020",
    status: false,
  },
  {
    title: 32,
    author: "Sonnnie Whalebelly",
    category: "Cyber security",
    tag: "Security",
    date: "1/12/2020",
    status: true,
  },
  {
    title: 33,
    author: "Norma Kunzler",
    category: "Cyber security",
    tag: "Health Tech",
    date: "2/11/2020",
    status: true,
  },
  {
    title: 34,
    author: "Opal Fitzmaurice",
    category: "Cyber security",
    tag: "Health Tech",
    date: "4/14/2020",
    status: true,
  },
  {
    title: 35,
    author: "Jesus Castanyer",
    category: "AI",
    tag: "Security",
    date: "12/16/2019",
    status: true,
  },
  {
    title: 36,
    author: "Helena Laville",
    category: "AI",
    tag: "Mobility",
    date: "6/12/2020",
    status: true,
  },
  {
    title: 37,
    author: "Starr Coltart",
    category: "AI",
    tag: "Health Tech",
    date: "6/5/2020",
    status: true,
  },
  {
    title: 38,
    author: "Crosby Della",
    category: "AI",
    tag: "Health Tech",
    date: "11/26/2019",
    status: false,
  },
  {
    title: 39,
    author: "Lewie Cornock",
    category: "AI",
    tag: "Mobility",
    date: "1/2/2020",
    status: false,
  },
  {
    title: 40,
    author: "Helsa Chestnutt",
    category: "Cyber security",
    tag: "Health Tech",
    date: "8/4/2020",
    status: true,
  },
  {
    title: 41,
    author: "Ford Renneke",
    category: "AI",
    tag: "Security",
    date: "10/5/2020",
    status: true,
  },
  {
    title: 42,
    author: "Ignazio Nenci",
    category: "Cyber security",
    tag: "Security",
    date: "7/15/2020",
    status: false,
  },
  {
    title: 43,
    author: "Brannon Petrescu",
    category: "AI",
    tag: "Mobility",
    date: "1/10/2020",
    status: true,
  },
  {
    title: 44,
    author: "Nanette Gosart",
    category: "Cyber security",
    tag: "Health Tech",
    date: "10/1/2020",
    status: false,
  },
  {
    title: 45,
    author: "Michaella Hoy",
    category: "AI",
    tag: "Mobility",
    date: "11/14/2020",
    status: true,
  },
  {
    title: 46,
    author: "Jacklyn Duffit",
    category: "AI",
    tag: "Security",
    date: "6/20/2020",
    status: false,
  },
  {
    title: 47,
    author: "Jacquette Bodell",
    category: "AI",
    tag: "Security",
    date: "1/18/2020",
    status: true,
  },
  {
    title: 48,
    author: "Arch Baudasso",
    category: "Cyber security",
    tag: "Security",
    date: "7/2/2020",
    status: true,
  },
  {
    title: 49,
    author: "Nikaniki McPherson",
    category: "AI",
    tag: "Security",
    date: "10/13/2020",
    status: false,
  },
  {
    title: 50,
    author: "Delores Dormand",
    category: "Cyber security",
    tag: "Security",
    date: "6/14/2020",
    status: false,
  },
];

export default content;
